# -*- coding: utf-8 -*-
"""Python 수업.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rGZCFHioHqSAEvKbXrS4kkYcrpUkrQC
"""

from google.colab import files
uploaded = files.upload()

import random
password = random.randrange(1,30)

tries = 0

name = input("너! 이름이 뭐니? : ")
print("{0}! 반가워 이제 비밀번호를 입력해 보자!".format(name))

'''for tries in range(1, 11):
    
    number = int(input("비밀 번호를 입력하세요 (1 ~ 30)"))
    
    if (password == number):
        print(" 비밀 번호가 맞습니다. 시도 횟수 [{0}]".format(tries))
        break
    
    elif(password<=number):
        print(" 입력하신 숫자가 너무 큽니다.")
    elif(password>=number):
        print(" 입력하신 숫자가 너무 작습니다.")
    
    if (tries == 10):
        print("입력횟수 10회를 초과 하였습니다.")
        break'''
    
while(tries<10):
    
    tries += 1

    try:
        x = input("비밀 번호를 입력하세요 (1 ~ 30)")
        
        number = int(x)

        if (password == number):
            print(" 비밀 번호가 맞습니다. 시도 횟수 [{0}]".format(tries))
            break
    
        elif(password<=number):
            print(" 입력하신 숫자가 너무 큽니다.")
        else:#(password>=number):
            print(" 입력하신 숫자가 너무 작습니다.")
    
        if (tries == 10):
            print("입력횟수 10회를 초과 하였습니다.")
            break 

    except:
        if (tries == 10):
            print("입력횟수 10회를 초과 하였습니다.")
            break 
       
        print("숫자를 입력하시오!")

'''
    if (password == number):
        print(" 비밀 번호가 맞습니다. 시도 횟수 [{0}]".format(tries))
        break
    
    elif(password<=number):
        print(" 입력하신 숫자가 너무 큽니다.")
    else:#(password>=number):
        print(" 입력하신 숫자가 너무 작습니다.")
    
    if (tries == 10):
        print("입력횟수 10회를 초과 하였습니다.")
        break    '''

import random
password = random.randrange(1,30)

tries = 0

name = input("너! 이름이 뭐니? : ")
print("{0}! 반가워 이제 비밀번호를 입력해 보자!".format(name))

while(tries<10):
    
    tries += 1

    try:
        number = int(input("비밀 번호를 입력하세요 (1 ~ 30)"))

        if (password == number):
            print(" 비밀 번호가 맞습니다. 시도 횟수 [{0}]".format(tries))
            break
    
        elif (password<=number):
            print(" 입력하신 숫자가 너무 큽니다.")
        else:
            print(" 입력하신 숫자가 너무 작습니다.")
    
        if (tries == 10):
            print("입력횟수 10회를 초과 하였습니다.")
            break 

    except:
        if (tries == 10):
            print("입력횟수 10회를 초과 하였습니다.")
            break 
       
        print("오류가 있습니다. 숫자를 다시 입력해주세요..")
        print("1~30의 정수만 입력이 가능합니다.")

import random
password = random.randrange(1,30)

tries = 0
trap = "k"

name = input("너! 이름이 뭐니? : ")
print("{0}! 반가워 이제 비밀번호를 입력해 보자!".format(name))

while(tries<10):
    tries += 1

    try:
        number = int(input("비밀번호를 입력하세요 :"))
        if number>30:
            trap = int(k)

    except:
        print("오류가 있습니다. 숫자를 다시 입력해주세요..")
        print("1~30의 정수만 입력이 가능합니다.")

    if (password == number):
        print(" 비밀 번호가 맞습니다. 시도 횟수 [{0}]".format(tries))
        break

    elif (password > number):
        print(" 입력하신 숫자가 너무 작습니다.")
    
    else:
        print("입력하신 숫자가 너무 큽니다.")

    if (tries == 10):
        print("입력 횟수를 초과 했습니다.")

def IsPrime(number):

    yaksu =0

    for i in range(1,number+1):
        if number % i ==0:
            yaksu = yaksu + 1

    if yaksu == 2:
        print(True)

    else:
        print(False)



while True:
    try:
        number = int(input("enter number ..."))
        break
    except ValueError:
        continue 
        
IsPrime(number)

while True:
    try:
        number = int(input("enter number ..."))
        break
    except ValueError:
        continue 

sosu = 0
for i in range(3,number+1):
    yaksu =0
    for j in range(1, i+1):
        if i % j ==0:
            yaksu = yaksu + 1

    if yaksu == 2:
        sosu = sosu + 1

print(sosu+1)

while True:
    try:
        number = int(input("숫자를 입력하세요 (1~10) : "))
        if number >10:
            continue
        break
    except ValueError:
        continue

i =1
star = "*"
while i <= number:
    if (number % i==0):
        print(star * i)
    i+=1

i=0
for i in range(1,6):
    print(i)

i =0
for i in range(1,6):
    print("{0} * {1} = {2}".format(9, i, 9*i))

s = 0

# 역순으로 돌릴수 있다.
for i in range(5,0,-1):
    s = s+i
    print("s:{0}".format(s))

while True:
    try:
        number = int(input("Enter Number.."))
        break
    except ValueError:
        continue

i =0
sum=0

for i in range(1,number+1):
    sum = sum + i

print("{0}까지의 합은 {1} 입니다.".format(number, sum))

while True:
    try:
        number1=int(input("Enter First Number.."))
        number2=int(input("Enter Second Number.."))
        pattern = int(input("증가값을 입력하시오.."))
        break
    except ValueError:
        continue
i=0
sum=0

for i in range(number1, number2+1,pattern):
    sum = sum + i

print("{0} 부터 {1} 까지 {2}간격으로 더한 값은 : {3}"\
      .format(number1, number2, pattern, sum))

while True:
    try:
        number = int(input("Enter Number.."))
        break
    except ValueError:
        continue

i =0
for i in range(1,10):
    print("{0} * {1} = {2}".format(number,i,number*i))

dan = 0;
row = 0;

for dan in range(2,10):
    if (dan == 9):
        print("#  {0}단  # \n".format(dan))
    else:
        print("#  {0}단  #".format(dan),end ="\t")
    
for row in range(1, 10):
    for dan in range(2, 10):
        if (dan==9):
            print("{0}X  {1}=  {2}\n".format(dan, row, dan*row))
        else:
            print("{0}X  {1}=  {2}".format(dan, row, dan*row),end = "\t")

aa = [10, 20, 30, 40]
print("aa[-1] = {0}, aa[-2] = {1}".format(aa[-1], aa[-2]))

print(aa[:3])
print(aa[2:4])

aa.append(50)
print(aa)

print(aa.pop())
bb = [20, 40, 10, 30, 50,]

print(bb)
bb.sort()
print(bb)

fruit = "banana"
letter = fruit[1]
print(letter)

print(len(fruit))

word = 'banana'
count = 0
for letter in word:
    if letter == 'a':
        count = count + 1
print(count)

'ban' in 'banana'

def IsPrime(number):

    yaksu =0

    for i in range(1,number+1):
        if number % i ==0:
            yaksu = yaksu + 1

    if yaksu == 2:
        print(True)

    else:
        print(False)



while True:
    try:
        number = int(input("enter number ..."))
        break
    except ValueError:
        continue 
        
IsPrime(number)

def numberOfPrime(number):
    sosu = 0
    for i in range(3,number+1):
        yaksu =0
        for j in range(1, i+1):
            if i % j ==0:
                yaksu = yaksu + 1

        if yaksu == 2:
            sosu = sosu + 1

    print(sosu+1)

while True:
    try:
        number = int(input("enter number ..."))
        break
    except ValueError:
        continue 

numberOfPrime(number)